### ISSUE TITLE
Some of the tools does not work

### ISSUE THREAD

**Issue by houshym** [jpetazzo/shpod#10]
I tried this container and it seems the following tools exist and other tools that mentioned such as K9s, kubeseal ... is not there
docker-compose  helm            httping         kctx            kns             kubectl         ship            stern
please check that

**Comment by jpetazzo** [comment]
Thanks for letting me know! It looks like something went wrong with the automated build last time. I updated the image manually, and now k9s and kubeseal are installed.

**Comment by houshym** [comment]
> Thanks for letting me know! It looks like something went wrong with the automated build last time. I updated the image manually, and now k9s and kubeseal are installed.
I suggest the following items:
1-Please update K8s manifest, So it pull latest image
2- set alias K for kubectl
3-Auto completion
4- krew does not work as I checked
5- kube-ps1 does not work too
